### ISSUE TITLE
Error 9 when getting totalMessageCount

### ISSUE THREAD

**Issue by tcurdt** [MailCore/MailCore#2]
I just changed the InboxLister example like this

```
NSSet *folders = [myAccount allFolders];
NSEnumerator *objEnum = [folders objectEnumerator];
NSString *folderName;
while((folderName = [objEnum nextObject])) {
    if (![@"[Gmail]" isEqualToString: folderName]) {
        CTCoreFolder *folder = [myAccount folderWithPath:folderName];
        NSLog(@"%@: %d", folderName, [folder totalMessageCount]);            
    }
}
```

and after a couple of folders it throws an exception with error 9.
This is connecting to imap.gmail.com with TLS port 993

Haven't had the time to dig deeper yet.

**Comment by tcurdt** [comment]
Exception is raised when "totalMessageCount" calls "mailfolder_connect". Looking at the enums this means a MAILIMAP_ERROR_PROTOCOL ...which is kind of surprising. One would think libeptan is mature and should not have that problem with Google's IMAP servers.

**Comment by tcurdt** [comment]
Interesting ...found the problem. Sort of. CTCoreFolder does not like to be autoreleased. Using init/release makes it work:

```
        CTCoreFolder *folder = [[CTCoreFolder alloc] initWithPath:folderName
                                                        inAccount:myAccount];
        NSLog(@"%@: %d", folderName, [folder totalMessageCount]);
        [folder release];
```

**Comment by MartinMReed** [comment]
If you are seeing this on Gmail it is because there is a 10 connection limit. You don't see the problem when you release manually because dealloc calls disconnect... but with autorelease the folders are not deallocated right away, and so the connections build up till you hit the max limit... and then you get the login error (9). You can still use autorelease, you just need to call disconnect on the folder instead of release.

Gmail page about IMAP connections:
http://support.google.com/mail/bin/answer.py?hl=en&answer=97150
