### ISSUE TITLE
32bit build fails on MacOS 10.6

### ISSUE THREAD

**Issue by HenningJ** [MailCore/MailCore#23]
When I tried to build MailCore (for Mac, not iOS) on my Mac (MacOs 10.6.8, Xcode 4.2) as 32bit version, the build fails with the following error message:

```
.../MailCore/Source/CTCoreMessage.m:57:43: error: synthesized property 'parentFolder' must either be named the same as a compatible ivar or must explicitly name an ivar [3]
 @synthesize mime=myParsedMIME, lastError, parentFolder;
```

Interestingly, building a 64bit version works fine. But since I need a 32/64bit version, that doesn't really help me.
Any ideas?

**Comment by mronge** [comment]
Ah, that error is because the 32bit version of Objective-C doesn't support auto-creating instance variables for properties. If you add an instance variable:

CTCoreFolder *parentFolder; 

to CTCoreMessage it should work. I recently added that and neglected to add the instance variable

## Any fixes you make I'd love to pull in with a pull request.

Matt Ronge

**Comment by HenningJ** [comment]
I figured that had to be the problem. I just wasn't aware that there were significant differences like this between the 32 and 64bit versions of Objective-C. Are there any more like that?

Oh well, making a little pull request right now.

**Comment by mronge** [comment]
Thanks! Merged in.

## Most of the "modern" Objective-C features the 32bit OS X runtime doesn't get sadly. Here is a little info: http://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtVersionsPlatforms.html#//apple_ref/doc/uid/TP40008048-CH106

Matt Ronge
